ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      DOUBLE PRECISION G__EXP__2,GH,GPHI,SQRT__AS,MP,MZ__EXP__2
     $ ,MZ__EXP__4,SQRT__2,MH__EXP__4,MT__EXP__4,MH__EXP__2,MT__EXP__2
     $ ,MH__EXP__12,MH__EXP__10,MH__EXP__8,MH__EXP__6,MT__EXP__6,AEW
     $ ,SQRT__AEW,EE,MW__EXP__2,SW2,CW,SQRT__SW2,SW,G1,GW,V,EE__EXP__2
     $ ,MW__EXP__12,MW__EXP__10,MW__EXP__8,MW__EXP__6,MW__EXP__4,AH
     $ ,V__EXP__2,LAM,YB,YT,YTAU,MUH,GW__EXP__2,CW__EXP__2,SW__EXP__2
     $ ,AEWM1,GF,AS,YMB,YMT,YMTAU

      COMMON/PARAMS_R/ G__EXP__2,GH,GPHI,SQRT__AS,MP,MZ__EXP__2
     $ ,MZ__EXP__4,SQRT__2,MH__EXP__4,MT__EXP__4,MH__EXP__2,MT__EXP__2
     $ ,MH__EXP__12,MH__EXP__10,MH__EXP__8,MH__EXP__6,MT__EXP__6,AEW
     $ ,SQRT__AEW,EE,MW__EXP__2,SW2,CW,SQRT__SW2,SW,G1,GW,V,EE__EXP__2
     $ ,MW__EXP__12,MW__EXP__10,MW__EXP__8,MW__EXP__6,MW__EXP__4,AH
     $ ,V__EXP__2,LAM,YB,YT,YTAU,MUH,GW__EXP__2,CW__EXP__2,SW__EXP__2
     $ ,AEWM1,GF,AS,YMB,YMT,YMTAU


      DOUBLE COMPLEX COMPLEXI

      COMMON/PARAMS_C/ COMPLEXI


