ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' External Params'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,*) 'aEWM1 = ', AEWM1
      WRITE(*,*) 'Gf = ', GF
      WRITE(*,*) 'aS = ', AS
      WRITE(*,*) 'ymb = ', YMB
      WRITE(*,*) 'ymt = ', YMT
      WRITE(*,*) 'ymtau = ', YMTAU
      WRITE(*,*) 'MT = ', MT
      WRITE(*,*) 'MB = ', MB
      WRITE(*,*) 'MZ = ', MZ
      WRITE(*,*) 'MH = ', MH
      WRITE(*,*) 'MTA = ', MTA
      WRITE(*,*) 'WT = ', WT
      WRITE(*,*) 'WZ = ', WZ
      WRITE(*,*) 'WW = ', WW
      WRITE(*,*) 'WH = ', WH
      WRITE(*,*)  ' Internal Params'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,*) 'sqrt__aS = ', SQRT__AS
      WRITE(*,*) 'G = ', G
      WRITE(*,*) 'CKM22 = ', CKM22
      WRITE(*,*) 'complexi = ', COMPLEXI
      WRITE(*,*) 'MZ__exp__2 = ', MZ__EXP__2
      WRITE(*,*) 'MZ__exp__4 = ', MZ__EXP__4
      WRITE(*,*) 'sqrt__2 = ', SQRT__2
      WRITE(*,*) 'MH__exp__2 = ', MH__EXP__2
      WRITE(*,*) 'aEW = ', AEW
      WRITE(*,*) 'MW = ', MW
      WRITE(*,*) 'sqrt__aEW = ', SQRT__AEW
      WRITE(*,*) 'ee = ', EE
      WRITE(*,*) 'MW__exp__2 = ', MW__EXP__2
      WRITE(*,*) 'sw2 = ', SW2
      WRITE(*,*) 'cw = ', CW
      WRITE(*,*) 'sqrt__sw2 = ', SQRT__SW2
      WRITE(*,*) 'sw = ', SW
      WRITE(*,*) 'g1 = ', G1
      WRITE(*,*) 'gw = ', GW
      WRITE(*,*) 'v = ', V
      WRITE(*,*) 'v__exp__2 = ', V__EXP__2
      WRITE(*,*) 'lam = ', LAM
      WRITE(*,*) 'yb = ', YB
      WRITE(*,*) 'yt = ', YT
      WRITE(*,*) 'ytau = ', YTAU
      WRITE(*,*) 'muH = ', MUH
      WRITE(*,*) 'gw__exp__2 = ', GW__EXP__2
      WRITE(*,*) 'cw__exp__2 = ', CW__EXP__2
      WRITE(*,*) 'ee__exp__2 = ', EE__EXP__2
      WRITE(*,*) 'sw__exp__2 = ', SW__EXP__2
      WRITE(*,*)  ' Internal Params evaluated point by point'
      WRITE(*,*)  ' ----------------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,*) 'G__exp__2 = ', G__EXP__2
