ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      DOUBLE PRECISION G__EXP__2,SQRT__AS,CKM22,MZ__EXP__2,MZ__EXP__4
     $ ,SQRT__2,MH__EXP__2,AEW,SQRT__AEW,EE,MW__EXP__2,SW2,CW
     $ ,SQRT__SW2,SW,G1,GW,V,V__EXP__2,LAM,YB,YT,YTAU,MUH,GW__EXP__2
     $ ,CW__EXP__2,EE__EXP__2,SW__EXP__2,AEWM1,GF,AS,YMB,YMT,YMTAU

      COMMON/PARAMS_R/ G__EXP__2,SQRT__AS,CKM22,MZ__EXP__2,MZ__EXP__4
     $ ,SQRT__2,MH__EXP__2,AEW,SQRT__AEW,EE,MW__EXP__2,SW2,CW
     $ ,SQRT__SW2,SW,G1,GW,V,V__EXP__2,LAM,YB,YT,YTAU,MUH,GW__EXP__2
     $ ,CW__EXP__2,EE__EXP__2,SW__EXP__2,AEWM1,GF,AS,YMB,YMT,YMTAU


      DOUBLE COMPLEX COMPLEXI

      COMMON/PARAMS_C/ COMPLEXI


