
all:
	cd src; make

install:
	cd src; make install

clean:
	cd src; make clean
	rm -f */*.o
	rm -f */*/*/*.o
	rm -f */*/*/*.a
	rm -f */*/*/*/*/*.o
	rm -f */*/*/*/*/*.a
	rm -f */*/*/*/*/*/*.o
	rm -f */*/*/*/*/*/*.a