ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' Couplings of heft'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,2) 'GC_8 = ', GC_8
      WRITE(*,2) 'GC_2 = ', GC_2
      WRITE(*,2) 'GC_3 = ', GC_3
      WRITE(*,2) 'GC_4 = ', GC_4
      WRITE(*,2) 'GC_27 = ', GC_27
      WRITE(*,2) 'GC_28 = ', GC_28
      WRITE(*,2) 'GC_29 = ', GC_29
      WRITE(*,2) 'GC_30 = ', GC_30
      WRITE(*,2) 'GC_44 = ', GC_44
