ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      DOUBLE PRECISION G
      COMMON/STRONG/ G

      DOUBLE COMPLEX GAL(2)
      COMMON/WEAK/ GAL


      DOUBLE PRECISION MB,MH,MT,MW,MTA,MZ

      COMMON/MASSES/ MB,MH,MT,MW,MTA,MZ


      DOUBLE PRECISION WW,WT,WZ,WH

      COMMON/WIDTHS/ WW,WT,WZ,WH


      DOUBLE COMPLEX GC_1, GC_2, GC_7, GC_16, GC_21, GC_22, GC_23
     $ , GC_25

      COMMON/COUPLINGS/ GC_1, GC_2, GC_7, GC_16, GC_21, GC_22, GC_23
     $ , GC_25

