ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' Couplings of sm'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,2) 'GC_1 = ', GC_1
      WRITE(*,2) 'GC_2 = ', GC_2
      WRITE(*,2) 'GC_7 = ', GC_7
      WRITE(*,2) 'GC_16 = ', GC_16
      WRITE(*,2) 'GC_21 = ', GC_21
      WRITE(*,2) 'GC_22 = ', GC_22
      WRITE(*,2) 'GC_23 = ', GC_23
      WRITE(*,2) 'GC_25 = ', GC_25
