ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      DOUBLE PRECISION G
      COMMON/STRONG/ G

      DOUBLE COMPLEX GAL(2)
      COMMON/WEAK/ GAL


      DOUBLE PRECISION MB,MH,MT,MW,MTA,MZ

      COMMON/MASSES/ MB,MH,MT,MW,MTA,MZ


      DOUBLE PRECISION WW,WT,WZ,WH

      COMMON/WIDTHS/ WW,WT,WZ,WH


      DOUBLE COMPLEX GC_21, GC_24

      COMMON/COUPLINGS/ GC_21, GC_24

